# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kata < Formula
  desc "Kata 形🤺 exercises"
  homepage "https://github.com/arvenil/kata"
  version "1.1.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arvenil/kata/releases/download/v1.1.6/kata_1.1.6_Darwin_x86_64.tar.gz"
      sha256 "74b69ef43bd512d87849b707c278777af32df99a6ebc6800fe155c7088bf032c"

      def install
        bin.install "bsearch"
        bin.install "ladder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arvenil/kata/releases/download/v1.1.6/kata_1.1.6_Linux_arm64.tar.gz"
      sha256 "5bb895c70ccc5f12758c15df24d2b1579af8127a75f7776176a9d4232f5b6a53"

      def install
        bin.install "bsearch"
        bin.install "ladder"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arvenil/kata/releases/download/v1.1.6/kata_1.1.6_Linux_x86_64.tar.gz"
      sha256 "d6208bfa636bb62816d31390bf3d25402deea0372f6b9020968f0afd3c0e2a02"

      def install
        bin.install "bsearch"
        bin.install "ladder"
      end
    end
  end

  test do
    system "#{bin}/bsearch -h"
    system "#{bin}/ladder -h"
  end
end
