# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kata < Formula
  desc "Kata 形🤺 exercises"
  homepage "https://github.com/arvenil/kata"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/arvenil/kata/releases/download/v1.0.1/kata_1.0.1_Darwin_x86_64.tar.gz"
    sha256 "03b1f8275b3936c5ff45f23a9d579b0e740b591d0a9200bfd6d49bbb82e16e6f"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/arvenil/kata/releases/download/v1.0.1/kata_1.0.1_Linux_x86_64.tar.gz"
    sha256 "e8dea841e8f2991307ea6cbf82b434b4a6467c9575697db586aaaa5c9562d413"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/arvenil/kata/releases/download/v1.0.1/kata_1.0.1_Linux_arm64.tar.gz"
    sha256 "a9f90bf2727d04d6c64a19d87af1090959901d64559eea27c64d860501a73afd"
  end

  def install
    bin.install "kata02"
    bin.install "kata19"
  end

  test do
    system "#{bin}/kata02 -h"
    system "#{bin}/kata19 -h"
  end
end
