# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kata < Formula
  desc "Kata 形🤺 exercises"
  homepage "https://github.com/arvenil/kata"
  version "1.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/arvenil/kata/releases/download/v1.1.3/kata_1.1.3_Darwin_arm64.tar.gz"
      sha256 "86e0bf20be1a946a70711515403b01842776ac1f5f77230490d0ab66879ada32"

      def install
        bin.install "bsearch"
        bin.install "ladder"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arvenil/kata/releases/download/v1.1.3/kata_1.1.3_Darwin_x86_64.tar.gz"
      sha256 "1cb058183cbae6baf13d08bebfa09c74cba4a843b23db6dd43139648bc69968c"

      def install
        bin.install "bsearch"
        bin.install "ladder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/arvenil/kata/releases/download/v1.1.3/kata_1.1.3_Linux_x86_64.tar.gz"
      sha256 "961c76dc7d20436ed10899fe02ab319c3392e11ea2eaf7e0b78e3f205ccc6380"

      def install
        bin.install "bsearch"
        bin.install "ladder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arvenil/kata/releases/download/v1.1.3/kata_1.1.3_Linux_arm64.tar.gz"
      sha256 "3057b6364638576510350a6ca4a4c7e9e3b2014b24681aea273d3259c043cf11"

      def install
        bin.install "bsearch"
        bin.install "ladder"
      end
    end
  end

  test do
    system "#{bin}/bsearch -h"
    system "#{bin}/ladder -h"
  end
end
